version: '3.5'

services:

  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:latest
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./data/roach1:/cockroach/cockroach-data"

networks:
  roachnet:
    driver: bridge